FROM python:3.10.11
WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r requirements.txt
COPY . .
EXPOSE 5002
ENV FLASK_APP=run.py
ENV FLASK_ENV = development
ENV FLASK_DEBUG=1
ENV FLASK_RUN_PORT=5002
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

#ENV MONGO_HOST=backapp-mongo-srv
ENV MONGO_HOST=localhost
ENV MONGO_PORT=27017
ENV MONGO_USER=EdCoachAI
ENV MONGO_PASSWORD=edcoach#2023@july
ENV TOKEN_EXPIRATION=3600
ENV PORT=5002
CMD ["flask", "run", "--host", "0.0.0.0"]